---
title: 'Liver - cell plots'
author: "Jon Thompson, Pers lab, rkm916 at ku dot dk"
date: "`r Sys.time()`" 
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
params: 
  date: !r substr(gsub("-","",as.character(Sys.Date())),3,1000)
  randomSeed: !r 12345
  pValThreshold: !r 0.05
# output:
#   html_notebook:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
#   html_document:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
---

# Setup

## Load packages

```{r}

library("Seurat")
library("data.table")
library("Matrix")
library("parallel")
library("dplyr")
library("ggplot2")
library("here")

```

## source utility functions

```{r}
source(here("perslab-sc-library", "utility_functions.R"))
source(here("perslab-sc-library", "functions_sc.R"))
```

## Set options

```{r}
options(stringsAsFactors = F, 
        use="pairwise.complete.obs", 
        warn=1, 
        verbose=F,
        boot.parallel="multicore", # see ?boot: each worker process inherits the environment of the current session, including the workspace and the loaded namespaces and attached packages (but not the random number seed: see below). 
        boot.ncpus = 20,
        mc.cores=40 # for parallel computation
        ) 

# data.table
setDTthreads(threads = NULL, 
             restore_after_fork = NULL)
getDTthreads()

#options(datatable.WhenJisSymbolThenCallingScope=TRUE)
```

## Set constants

```{r}
randomSeed = 12345
set.seed(randomSeed)

# maxit = 100 # for rlm, see users.stat.umn.edu/~sandy/courses/8053/handouts/robust.pdf
flagDate =substr(gsub("-","",as.character(Sys.Date())),3,1000)

```

generic project constants 

```{r}
prefixData = "liver_perslab_int"
prefixRun = "seurat_7"
```

## load data

```{r}
seuratObj <- readRDS(here("output","liver_perslab_int_seurat_7_SCTint_perslab_labels_seuratObj.RDS.gz"))
```

```{r}
#dt_geneMod_perslab = 
```

```{r}
# dt_markers <- openxlsx::read.xlsx(here("output","liver_perslab_align_seurat_7_SCTransformIntegrated_clustermarkers.xlsx"))
# head(dt_markers)
```

```{r}
Seurat::DefaultAssay(seuratObj) <-"SCT_combat"
```

get coarse cluster marker genes

```{r}
clusters = seuratObj@meta.data$cluster_perslab_coarse %>% table %>% names 

Seurat::Idents(seuratObj) <-seuratObj@meta.data$cluster_perslab_coarse

list_iterable = list("X"=clusters)
fun = function(cluster) {tryCatch({
  FindMarkers(seuratObj ,  
          #cells.1=colnames(seurat_obj)[Idents(seurat_obj)==cluster],
          #cells.2=NULL,
          ident.1 = cluster,
          only.pos = T,
          #ident.2 = clusters[clusters!=cluster],
          test.use  ="wilcox",
          max.cells.per.ident=1000,
          random.seed=randomSeed,
          #latent.vars = if (!is.null(merge_specify) | !is.null(merge_group_IDs)) "sample_ID" else NULL,
          verbose = T)
          }, 
          error = function(err) {
            NA_character_
            warning(paste0("findmarkers failed for ", cluster, " with error "))
          })}

list_markers=NULL
list_markers <- lapply(FUN=fun, "X"=list_iterable[[1]])

# add the gene and cluster as a column
list_markers <- mapply(function(df_markers, cluster) {
  if (!all(sapply(df_markers, is.na))) {
    cbind("gene" = rownames(df_markers), "cluster"=rep(cluster, nrow(df_markers)), df_markers)
  } else {
    NA_character_
  }
},
df_markers=list_markers, 
cluster=clusters, SIMPLIFY=F)

list_markers <- list_markers[!sapply(list_markers, function(markers) all(is.na(markers)))]
df_markers <- Reduce(x=list_markers, f=rbind)
rownames(df_markers) <- NULL

saveMeta(savefnc=openxlsx::write.xlsx, x = df_markers, file=here("output", paste0(prefixData, "_", prefixRun, "coarse_clustermarkers_", flagDate,".xlsx")))

```

```{r}
dt_markers = setDT(df_markers)
```


## plotting

### dot plot

```{r}

list_markers <- lapply(clusters, function(clust){
  #clust_num <- gsub("-.*","",clust)
  mycondition = quote(dt_markers$cluster==clust)
  dt_markers[eval(mycondition),"gene"][1:10]
})
names(list_markers) <- clusters
vec_markers <- unlist(list_markers, use.names = T)
names(vec_markers) <- gsub("\\.|gene\\d+$","", names(vec_markers))
head(vec_markers)
tail(vec_markers)
```

```{r}
factor_cell_clust_group <- factor(clusters, ordered = T)
```

```{r}
vec_markers = unique(vec_markers)
```

```{r,fig.width=18, fig.height=7}

p<-DotPlot_timshel(
  object=seuratObj,
  assay="SCT_combat",
  slot = "data",
  do.scale=T,
  genes.plot=rev(vec_markers),#rev(df$gene_name),
  cols.use = c("blue","white", "red"),#brewer.pal(n=11,"Spectral"),#c("blue","red"),
  col.min = -2.5,
  col.max = 2.5,
  dot.min = 0,
  dot.scale = 6,
  group.by="cluster_perslab_coarse",
  group.order=factor_cell_clust_group,
  plot.legend = T,
  do.return = T,
  x.lab.rot = T,
  coord_flip = F,
  df.marker.panel.to.plot=NULL#df
)
saveMeta(savefnc= ggsave, plot= p, filename = here("plots", paste0(prefixData, "_", prefixRun, "_SCT_combat_clust_coarse_markergene_dotplot",flagDate,".pdf")), width = 25, height=6)
```

### feature plots

```{r}
genes = c("TREM2")
```

```{r,fig.width=10}
Seurat::FeaturePlot(object=seuratObj, features="TREM2")
```

```{r}
vec_mods = c("aquamarine", "brown", "mediumaquamarine")
```

```{r}
DefaultAssay(object = seuratObj) = "integrated"
```

```{r}
p <- Seurat::FeaturePlot(object=seuratObj, features=vec_mods, blend = F, order = T)
saveMeta(savefnc= ggsave, plot= p, filename = here("plots", paste0(prefixData, "_", prefixRun, "_", prefixOut, "_mod_featplots_",flagDate,".pdf")), width = 12, height=12)
```

### violin plots

```{r}
vec_genes = c("VCAN")
```

```{r}
DefaultAssay(seuratObj) = "SCT_combat"
```

```{r}
#list_seuratObj[[1]]$macs_subclust <- factor(list_seuratObj[[1]]$macs_subclust, levels = 0:6, ordered=T)
for (gene in vec_genes) {
  p <- Seurat::VlnPlot(object = seuratObj, 
                       features = vec_genes,
                       assay = "SCT_combat", 
                       slot = "data", 
                       log=FALSE,
                       sort = F, 
                       group.by = "cluster_perslab")
  
  ggsave(plot = p, filename = here("plots", paste0(prefixData, "_",prefixRun, "_",gene,"_vlnplot_", params$date, ".pdf")), width = 12, height=9)
}
```

## bar plot

sc wgcna modules

```{r}

dt_geneMod_perslab_merged$module_pres %>% unique -> vec_mods_perslab

vec_mods_perslab<- vec_mods_perslab[!is.na(vec_mods_perslab) & nchar(vec_mods_perslab)>0]

mat_embed_perslab <- sapply(vec_mods_perslab, function(mod) {

  # get gene weights
  condition = quote(dt_geneMod_perslab_merged[[colModule]]==mod)
  vec_pkMs <- dt_geneMod_perslab_merged[eval(condition), pkMs,]

  # normalize module gene weights to sum to 1
  vec_pkMs <- vec_pkMs/sum(vec_pkMs)

  # find corresponding rows of the expression matrix
  vec_idxRow <- match(dt_geneMod_perslab_merged[eval(condition), ..colGeneNames, ][[1]], dt_datExpr[,gene])

  # filter out mis-matches
  vec_pkMs <- vec_pkMs[!is.na(vec_idxRow)]
  vec_idxRow <- vec_idxRow[!is.na(vec_idxRow)]

  # compute weighted sum of normalized expression
  dt_datExpr[vec_idxRow,-("gene")] %>% as.matrix -> mat_sub

  vec_pkMs %*% mat_sub

})

rownames(mat_embed_perslab) <- colnames(dt_datExpr)[-1]

mat_embed_perslab[0:4,0:4]
```
