---
title: 'Liver - gene network geneset tests'
author: "Jon Thompson, Pers lab, rkm916 at ku dot dk"
date: "`r Sys.time()`" 
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
params: 
  date: !r substr(gsub("-","",as.character(Sys.Date())),3,1000)
  randomSeed: !r 12345
  pValThreshold: !r 0.05
# output:
#   html_notebook:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
#   html_document:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
---

# Setup

## Load packages

```{r}

library("Seurat")
library("data.table")
library("Matrix")
library("parallel")
library("dplyr")
library("ggplot2")
library("here")

```

## source utility functions

```{r}
source(here("/perslab-sc-library", "utility_functions.R"))
source(here("perslab-sc-library", "functions_sc.R"))
```

## Set options

```{r}
options(stringsAsFactors = F, 
        use="pairwise.complete.obs", 
        warn=1, 
        verbose=F,
        boot.parallel="multicore", # see ?boot: each worker process inherits the environment of the current session, including the workspace and the loaded namespaces and attached packages (but not the random number seed: see below). 
        boot.ncpus = 20,
        mc.cores=40 # for parallel computation
        ) 

# data.table
setDTthreads(threads = NULL, 
             restore_after_fork = NULL)
getDTthreads()

#options(datatable.WhenJisSymbolThenCallingScope=TRUE)
```

## Set constants

```{r}
randomSeed = 12345
set.seed(randomSeed)

npcs=40
res_primary = 0.8
pval.adjust.method = "BH"
pValThreshold = 0.05#params$pValThreshold

# maxit = 100 # for rlm, see users.stat.umn.edu/~sandy/courses/8053/handouts/robust.pdf
flagDate =substr(gsub("-","",as.character(Sys.Date())),3,1000)

```


generic project constants 

```{r}

prefixData = "liver_perslab_int"
prefixRun = "seurat_7"
#prefixOut <- "SCT"
prefixOut <- "macrophages"


dirWGCNA_outs = "/projects/jonatan/pub-perslab/18-liver-wgcna/"
dirWGCNA_plots = paste0(dirWGCNA_outs, "plots/" )
dirWGCNA_RObjects = paste0(dirWGCNA_outs, "RObjects/" )
dirWGCNA_tables = paste0(dirWGCNA_outs, "tables/" )

colGeneWeights = "pkMs"
colGeneNames = "genes"
colModule = "module_merged"
colCellCluster = "cell_cluster_merged"
```

## load data

```{r}
seuratObj_sub <- readRDS(here("output","liver_perslab_int_seurat_7_SCTint_perslab_labels_seuratObj_macroph.RDS.gz"))
#seuratObj <- readRDS(here("output","liver_perslab_int_seurat_7_SCTint_perslab_labels_seuratObj.RDS.gz"))
```

```{r}
seuratObj_combat <- readRDS(here("output","liver_perslab_int_seurat_7_SCTint_perslab_labels_seuratObj_combat.RDS.gz"))
```

```{r}
path_geneMod <- paste0(dirWGCNA_tables,"liver_perslab_int_wgcna2_cell_cluster_module_genes_subCellClusters_merged.csv.gz")
  
dt_geneMod <- fread(path_geneMod)

head(dt_geneMod)
```

## subset and run standard clustering workflow on integrated data


```{r}
Idents(seuratObj_combat) <- "cluster_perslab_coarse"
```

```{r}
seuratObj_combat_sub <- subset(seuratObj_combat, idents = "Macrophages")
```

```{r}
if (F){
  Idents(seuratObj) <- seuratObj$cluster_perslab_coarse
  DefaultAssay(seuratObj) <- "integrated"
}
```

```{r}
if (F){ 
  seuratObj_sub <- subset(seuratObj, idents = "Macrophages" )
}
```

```{r}
if (F){ 
  seuratObj_sub <- Seurat::RunPCA(seuratObj_sub, 
                                assay = "integrated",
                                npcs = npcs, 
                                seed.use=randomSeed,
                                verbose = FALSE)
}
```

```{r}
if (F){
seuratObj_sub <- FindNeighbors(object = seuratObj_sub, dims= 1:npcs, verbose = T)
seuratObj_sub <- FindClusters(object = seuratObj_sub, verbose = T,resolution =res_primary, random.seed = randomSeed)
}
```

```{r}
if (F){
seuratObj_sub <- RunUMAP(object=seuratObj_sub, 
                               dims=1:npcs, 
                               reduction = "pca",
                               assay=  "integrated", 
                               seed.use = randomSeed)
}
```

```{r}
p1 <-DimPlot(seuratObj_sub, 
             reduction = 'umap', 
             group.by = paste0(DefaultAssay(seuratObj_sub),'_snn_res.',res_primary),
             label = TRUE)

saveMeta(savefnc= ggsave, plot= p1, filename = here("plots", paste0(prefixData, "_", prefixRun, "_", prefixOut, "_UMAP_clust.pdf")), width = 20, height=12)
```

```{r}
DefaultAssay(seuratObj_sub) <- "SCTall"
```

```{r}
FeaturePlot(seuratObj_sub, "TREM2")
```

```{r}
vec_idx <- which(seuratObj_sub@assays$SCTall@counts["TREM2",]>0 & seuratObj_sub@assays$SCTall@counts["CD9",]>0)
vec_cellIDs = colnames(seuratObj_sub@assays$SCTall@counts)[vec_idx]
```

```{r}
seuratObj_sub_TREM2plus_CD9plus <- subset(seuratObj_sub, cells = vec_cellIDs)
table(seuratObj_sub_TREM2plus_CD9plus$sample_ID)
```

get marker genes

```{r}
clusters = seuratObj_sub@meta.data[[paste0(DefaultAssay(seuratObj_sub),"_snn_res.", res_primary)]] %>% table %>% names 
Idents(seuratObj_sub) <-seuratObj_sub@meta.data[[paste0(DefaultAssay(seuratObj_sub),"_snn_res.", res_primary)]]

list_iterable = list("X"=clusters)
fun = function(cluster) {tryCatch({
  FindMarkers(seuratObj_sub ,  
              #cells.1=colnames(seurat_obj)[Idents(seurat_obj)==cluster],
              #cells.2=NULL,
              ident.1 = cluster,
              only.pos = T,
              #ident.2 = clusters[clusters!=cluster],
              test.use  ="MAST",
              max.cells.per.ident=1000,
              random.seed=randomSeed,
              #latent.vars = if (!is.null(merge_specify) | !is.null(merge_group_IDs)) "sample_ID" else NULL,
              verbose = T)
}, 
error = function(err) {
  NA_character_
})}
list_markers=NULL
list_markers <- lapply(FUN=fun, "X"=list_iterable[[1]])

# add the gene and cluster as a column
list_markers <- mapply(function(df_markers, cluster) {
  if (!all(sapply(df_markers, is.na))) {
    cbind("gene" = rownames(df_markers), "cluster"=rep(cluster, nrow(df_markers)), df_markers)
  } else {
    NA_character_
  }
},
df_markers=list_markers, 
cluster=names(table(Idents(seuratObj_sub))), SIMPLIFY=F)

list_markers <- list_markers[!sapply(list_markers, function(markers) all(is.na(markers)))]
df_markers <- Reduce(x=list_markers, f=rbind)
rownames(df_markers) <- NULL
```

## featureplots 

```{r}
DefaultAssay(seuratObj_sub) <- "RNA"
```

```{r}
FeaturePlot(object = seuratObj_sub, features = "DUOXA1")
```

```{r}
FeaturePlot(object=seuratObj_combat_sub,features = "DUOXA1")
```

```{r}
FeaturePlot(object = seuratObj_combat, features = "DUOXA1")
```




## wrap up

```{r}
saveMeta(savefnc=openxlsx::write.xlsx, x = df_markers, file=here("data", paste0(prefixData, "_", prefixRun, "_", prefixOut, "_clustermarkers.xlsx")))
```

```{r}
saveRDS(seuratObj_sub, here("output","liver_perslab_int_seurat_7_SCTint_perslab_labels_seuratObj_macroph.RDS.gz"))
```

