---
title: 'Liver - gene network geneset tests'
author: "Jon Thompson, Pers lab, rkm916 at ku dot dk"
date: "`r Sys.time()`" 
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
params: 
  date: !r substr(gsub("-","",as.character(Sys.Date())),3,1000)
  randomSeed: !r 12345
  pValThreshold: !r 0.05
# output:
#   html_notebook:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
#   html_document:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
---

# Setup

## Load packages

```{r}

library("data.table")
library("Matrix")
library("Seurat")
library("here")
library("magrittr")
```

## source utility functions

```{r}
source(here("/perslab-sc-library", "utility_functions.R"))
source(here("perslab-sc-library", "functions_sc.R"))
```

## Set options

```{r}
options(stringsAsFactors = F, 
        use="pairwise.complete.obs", 
        warn=1, 
        verbose=F,
        boot.parallel="multicore", # see ?boot: each worker process inherits the environment of the current session, including the workspace and the loaded namespaces and attached packages (but not the random number seed: see below). 
        boot.ncpus = 20,
        mc.cores=40 # for parallel computation
        ) 

```

## Set constants

```{r}
randomSeed = 12345
set.seed(randomSeed)

```


generic project constants 

```{r}

prefixData = "liver_perslab_int"
prefixRun = "seurat_7"
prefixOut <- "SCTint"

```

## load data

```{r}
pathSeuratObj <- "/nfsdata/projects/jonatan/pub-perslab/18-liver-fred/output/liver_perslab_int_seurat_7_SCTint_perslab_labels_seuratObj.RDS.gz"
  #dir(path=here("output"), pattern = paste0(".*",prefixRun, ".*\\.RDS\\.gz"), full.names = T)
seuratObj <- load_obj(pathSeuratObj)
```

## pre-processing

check that the cells in the @counts slot are the same as those in the @data slot (no filtering)

```{r}
dim(seuratObj@assays$RNA@counts)
# [1] 36116 21007
dim(seuratObj@assays$RNA@data)
# [1] 36116 21007
```

```{r}
DefaultAssay(seuratObj) <- "RNA"
```

Get raw counts

```{r}
dt_counts <- GetAssayData(object=seuratObj, slot ="counts") %>% as.data.table
dt_counts <- data.table("gene"=rownames(seuratObj), dt_counts)

dt_counts[0:5,0:5]

#            gene AAACCTGAGCGTGAAC_1 AAACCTGAGCTCCTCT_1 AAACGGGCATGCAATC_1
# 1:   MIR1302-10                  0                  0                  0
# 2:      FAM138A                  0                  0                  0
# 3:        OR4F5                  0                  0                  0
# 4: RP11-34P13.7                  0                  0                  0
# 5: RP11-34P13.8                  0                  0                  0
#    AAAGATGTCCACGACG_1
# 1:                  0
# 2:                  0
# 3:                  0
# 4:                  0
# 5:                  0
```

map genes to ensembl as apparently CELLEX doesn't do this

```{r}
dt_mapping <- fread("/projects/jonatan/tools/data/gene_annotation_hsapiens.txt.gz")
head(dt_mapping)
```

```{r}
dt_counts <- gene_map(dataIn = dt_counts, colGene = "gene", replace=T, df_mapping = dt_mapping, from="hgnc_symbol", to="ensembl_gene_id", na.rm=T)
```

get metadata cell_ID and celltype

```{r}
dt_metadata <- data.table("cell_id"= colnames(seuratObj), "cell_type"=seuratObj$cluster_perslab)
```

## write out to disk

```{r}
# counts 
path_counts <- here("data", paste0(prefixData, "_", prefixRun, "_counts.csv"))
saveMeta(savefnc = fwrite, x =dt_counts, file = path_counts)
system2(command="gzip", args = path_counts)
# metadata
path_metadata <- here("data", paste0(prefixData, "_", prefixRun, "_metadata.csv"))
saveMeta(savefnc = fwrite, x =dt_metadata, file = path_metadata)

```


