---
title: 'Liver project Seurat QC'
author: "Jon Thompson, Pers lab"
date: "`r Sys.time()`" 
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
params: 
  date: !r substr(gsub("-","",as.character(Sys.Date())),3,1000)
  randomSeed: !r 12345
  pValThreshold: !r 0.05
---

# Setup 

## options

```{r}
options(stringsAsFactors = F, 
        use="pairwise.complete.obs", 
        warn=1, 
        verbose=F,
        mc.cores=40 # for parallel computation
        ) 
```

```{r}
randomSeed = 12345
set.seed(randomSeed)
```

Source functions

```{r}
# change to submodule within project
source("./perslab-sc-library/utility_functions.R")
```

## Load packages

```{r}
ipak(c("Seurat", "dplyr", "Matrix", "parallel", "readxl", "ggplot2", "cowplot"))
```

## Set session parameters and constants

```{r}

dirProject = "/projects/jonatan/pub-perslab/18-liver-fred/"
dirAnalysis = paste0(dirProject, "/analysis/")
dirOutput = paste0(dirProject, "/output/")
dirPlots = paste0(dirProject, "/plots/")
dirLog = paste0(dirProject, "/log/")
dirTables = paste0(dirProject, "/tables/")

prefixData = "liver_perslab_align"
prefixRun = "seurat_7"
```

## load data

```{r}
pathSeuratObj <- dir(path=dirOutput, pattern = paste0(".*",prefixRun, ".*\\.RDS\\.gz"), full.names = T)
seuratObj <- load_obj(pathSeuratObj)
```


### Visualise effects of different mito/ribo cutoffs

```{r}
seuratObj$percent.ribo_0.28 <- seuratObj$percent.ribo <= 0.28 
seuratObj$percent.ribo_0.26 <- seuratObj$percent.ribo <= 0.26
seuratObj$percent.ribo_0.24 <- seuratObj$percent.ribo <= 0.24
seuratObj$percent.ribo_0.22 <- seuratObj$percent.ribo <= 0.22 
seuratObj$percent.ribo_0.20 <- seuratObj$percent.ribo <= 0.20
seuratObj$percent.ribo_0.18 <- seuratObj$percent.ribo <= 0.18
seuratObj$percent.ribo_0.16 <- seuratObj$percent.ribo <= 0.16
seuratObj$percent.ribo_0.14 <- seuratObj$percent.ribo <= 0.14
seuratObj$percent.ribo_0.14 <- seuratObj$percent.ribo <= 0.12
```

```{r}
seuratObj$percent.mito_0.38 <- seuratObj$percent.mito <= 0.38
seuratObj$percent.mito_0.36 <- seuratObj$percent.mito <= 0.36
seuratObj$percent.mito_0.34 <- seuratObj$percent.mito <= 0.34
seuratObj$percent.mito_0.32 <- seuratObj$percent.mito <= 0.32
seuratObj$percent.mito_0.30 <- seuratObj$percent.mito <= 0.30
seuratObj$percent.mito_0.28 <- seuratObj$percent.mito <= 0.28
seuratObj$percent.mito_0.26 <- seuratObj$percent.mito <= 0.26
seuratObj$percent.mito_0.24 <- seuratObj$percent.mito <= 0.24
seuratObj$percent.mito_0.22 <- seuratObj$percent.mito <= 0.22
seuratObj$percent.mito_0.20 <- seuratObj$percent.mito <= 0.20
seuratObj$percent.mito_0.18 <- seuratObj$percent.mito <= 0.18
seuratObj$percent.mito_0.16 <- seuratObj$percent.mito <= 0.16
seuratObj$percent.mito_0.14 <- seuratObj$percent.mito <= 0.14
```

```{r, fig.height=12, fig.height=12}

list_plot <- lapply("X"=grep(pattern="percent.ribo_0\\.\\d{2}$",x = colnames(seuratObj@meta.data), value=T), FUN = function(groupName) {
  DimPlot(object = seuratObj,  group.by=groupName, pt.size = 0.75, title = groupName)
}) 

p1<- cowplot::plot_grid(plotlist = list_plot,
                        ncol= (list_plot %>% length %>% sqrt %>% as.integer),
                        labels=as.list(grep(pattern="percent.ribo_0\\.\\d{2}$",x = colnames(seuratObj@meta.data), value=T)))

saveMeta(savefnc = cowplot::save_plot, plot=p1,
          ncol= (list_plot %>% length %>% sqrt %>% as.integer),
          filename =  paste0(dirPlots, prefixData, "_", prefixRun, "_ribo_QCplotgrid.pdf"),
          base_height = 15, # of a subplot
          #base_width = 5,
          base_aspect_ratio = 0.4,
          limitsize=F)
```



```{r, fig.height=12, fig.height=12}

list_plot <- lapply("X"=grep(pattern="percent.mito_0\\.\\d{2}$",x = colnames(seuratObj@meta.data), value=T), FUN = function(groupName) {
  DimPlot(object = seuratObj,  group.by=groupName, pt.size = 0.75, title = groupName)
}) 

p1<- cowplot::plot_grid(plotlist = list_plot,
                        ncol= (list_plot %>% length %>% sqrt %>% as.integer), 
                        labels=as.list(grep(pattern="percent.mito_0\\.\\d{2}$",x = colnames(seuratObj@meta.data), value=T)))

saveMeta(savefnc = cowplot::save_plot, plot=p1,
          ncol= (list_plot %>% length %>% sqrt %>% as.integer),
          filename =  paste0(dirPlots, prefixData, "_", prefixRun, "_mito_QCplotgrid.pdf"),
          base_height = 15, # of a subplot
          #base_width = 5,
          base_aspect_ratio = 0.4,
          limitsize=F)
```

### Visualise effects of different min nCount_RNA cutoffs
```{r}

seuratObj$min_nCount_RNA_1050 <- seuratObj$nCount_RNA >= 1050
seuratObj$min_nCount_RNA_1100 <- seuratObj$nCount_RNA >= 1100
seuratObj$min_nCount_RNA_1150 <- seuratObj$nCount_RNA >= 1150
seuratObj$min_nCount_RNA_1200 <- seuratObj$nCount_RNA >= 1200
seuratObj$min_nCount_RNA_1250 <- seuratObj$nCount_RNA >= 1250
seuratObj$min_nCount_RNA_1300 <- seuratObj$nCount_RNA >= 1300
seuratObj$min_nCount_RNA_1350 <- seuratObj$nCount_RNA >= 1350
seuratObj$min_nCount_RNA_1400 <- seuratObj$nCount_RNA >= 1400
seuratObj$min_nCount_RNA_1450 <- seuratObj$nCount_RNA >= 1450
seuratObj$min_nCount_RNA_1500 <- seuratObj$nCount_RNA >= 1500

```
 
```{r, fig.height=12, fig.height=12}

list_plot <- lapply("X"=grep(pattern="min_nCount_RNA_.+",x = colnames(seuratObj@meta.data), value=T), FUN = function(groupName) {
  DimPlot(object = seuratObj,  group.by=groupName, pt.size = 0.75, title = groupName)
}) 

p1<- cowplot::plot_grid(plotlist = list_plot,
                          ncol= (list_plot %>% length %>% sqrt %>% as.integer),
                        labels  = as.list(grep(pattern="min_nCount_RNA_.+",x = colnames(seuratObj@meta.data), value=T)))

saveMeta(savefnc = cowplot::save_plot, plot=p1,
          ncol= (list_plot %>% length %>% sqrt %>% as.integer),
          filename =  paste0(dirPlots, prefixData, "_", prefixRun, "_min_nCount_RNA_QCplotgrid.pdf"),
          base_height = 15, # of a subplot
          #base_width = 5,
          base_aspect_ratio = 0.4,
          limitsize=F)
```

## Filter on QC variables

```{r}
seuratObjFilter <- Seurat::SubsetData(object = seuratObj, subsetname = "percent.mito", high.threshold= 0.4) 
seuratObj
seuratObjFilter
```

```{r}
seuratObjFilter <- Seurat::SubsetData(object = seuratObj, subsetname = "percent.ribo", high.threshold= 0.3) 
seuratObj
seuratObjFilter
```

