---
title: 'Liver - compute overlap of bulk with sc modules'
author: "Jon Thompson, Pers lab, rkm916 at ku dot dk"
date: "`r Sys.time()`" 
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
params: 
  date: !r substr(gsub("-","",as.character(Sys.Date())),3,1000)
  randomSeed: !r 12345
  pValThreshold: !r 0.05
# output:
#   html_notebook:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
#   html_document:
#     df_print: paged
#     number_sections: yes
#     toc: yes
#     toc_depth: 3
#     toc_float: yes
---

previous: liver_module_rename.Rmd

# Setup

## Load packages

```{r}
library("dplyr")
library("Matrix")
library("parallel")
library("readr")
library("openxlsx")
library("data.table")
library("here")
library("corrplot")
library("RColorBrewer")

# source utility functions


source(here("/perslab-sc-library", "utility_functions.R"))
source(here("perslab-sc-library", "functions_sc.R"))

# Set options

options(stringsAsFactors = F, 
        use="pairwise.complete.obs", 
        warn=1, 
        verbose=F,
        boot.parallel="multicore", # see ?boot: each worker process inherits the environment of the current session, including the workspace and the loaded namespaces and attached packages (but not the random number seed: see below). 
        boot.ncpus = 20,
        mc.cores=40 # for parallel computation
        ) 

RNGkind("L'Ecuyer-CMRG")
# ?boot
# For most of the boot methods the resampling is done in the master process, but not if simple = TRUE nor sim = "parametric". In those cases (or where statistic itself uses random numbers), more care is needed if the results need to be reproducible. Resampling is done in the worker processes by censboot(sim = "wierd") and by most of the schemes in tsboot (the exceptions being sim == "fixed" and sim == "geom" with the default ran.gen).
# 
# Where random-number generation is done in the worker processes, the default behaviour is that each worker chooses a separate seed, non-reproducibly. However, with parallel = "multicore" or parallel = "snow" using the default cluster, a second approach is used if RNGkind("L'Ecuyer-CMRG") has been selected. In that approach each worker gets a different subsequence of the RNG stream based on the seed at the time the worker is spawned and so the results will be reproducible if ncpus is unchanged, and for parallel = "multicore" if parallel::mc.reset.stream() is called: see the examples for mclapply. 

# data.table
setDTthreads(threads = NULL, 
             restore_after_fork = NULL)
getDTthreads()

# Set constants

randomSeed = 12345
set.seed(randomSeed)

pAdjustMethod = "BH"
pValThreshold = 0.05#params$pValThreshold

nRep = 10000 # bootstrap replicates
# maxit = 100 # for rlm, see users.stat.umn.edu/~sandy/courses/8053/handouts/robust.pdf

flagDate =substr(gsub("-","",as.character(Sys.Date())),3,1000)


# generic project constants 

prefixData = "liver_perslab_int"
prefixRun = "seurat_7"
prefixRun_WGCNA = "wgcna3"

dirWGCNA_outs = "/projects/jonatan/pub-perslab/18-liver-wgcna/"
dirWGCNA_plots = paste0(dirWGCNA_outs, "plots/" )
dirWGCNA_RObjects = paste0(dirWGCNA_outs, "RObjects/" )
dirWGCNA_tables = paste0(dirWGCNA_outs, "tables/" )

colGeneWeights = "pkMs"
colGeneNames = "genes"
colModule = "module_renamed"
colCellCluster = "cell_cluster_pres"
```

## load data

Load modules dataframes

```{r}
dt_geneMod_perslab <- fread("/projects/jonatan/pub-perslab/18-liver-wgcna/tables/liver_perslab_int_wgcna3_geneMod.csv.gz")
#head(dt_geneMod_perslab)

dt_geneMod_gerhard2018 <- fread("/projects/jonatan/pub-perslab/18-liver-wgcna/tables/liver_gerhard2018_wgcna3_geneMod.csv.gz")
#head(dt_geneMod_gerhard2018)

# dt_geneMod_moylan2013 <- fread("/projects/jonatan/pub-perslab/18-liver-wgcna/tables/liver_moylan2013_wgcna1_geneMod.csv.gz")
#head(dt_geneMod_moylan2013 )
```

## get lists of module gene vectors

```{r}
vec_mod_perslab = unique(dt_geneMod_perslab[[colModule]])
vec_mod_perslab = vec_mod_perslab[nchar(vec_mod_perslab)>0]

list_vec_modGenes_perslab = lapply(vec_mod_perslab, function(module){
  dt_geneMod_perslab[[colGeneNames]] %>% '['(dt_geneMod_perslab[[colModule]]==module) %>% na.omit -> geneNames
  geneNames[nchar(geneNames)>0]
})

names(list_vec_modGenes_perslab) = vec_mod_perslab
```

```{r}
vec_mod_gerhard2018 = unique(dt_geneMod_gerhard2018[[colModule]])
vec_mod_gerhard2018 = vec_mod_gerhard2018[nchar(vec_mod_gerhard2018)>0]
list_vec_modGenes_gerhard2018 = lapply(vec_mod_gerhard2018, function(module){
  dt_geneMod_gerhard2018[[colGeneNames]] %>% '['(dt_geneMod_gerhard2018[[colModule]]==module) %>% na.omit -> geneNames
  geneNames[nchar(geneNames)>0]
})

names(list_vec_modGenes_gerhard2018) = vec_mod_gerhard2018
```

<!-- ```{r} -->
<!-- vec_mod_moylan2013 = unique(dt_geneMod_moylan2013[[colModule]]) -->
<!-- vec_mod_moylan2013 = vec_mod_moylan2013[nchar(vec_mod_moylan2013)>0] -->
<!-- list_vec_modGenes_moylan2013 = lapply(vec_mod_moylan2013, function(module){ -->
<!--   dt_geneMod_moylan2013[[colGeneNames]] %>% '['(dt_geneMod_moylan2013[[colModule]]==module) %>% na.omit -> geneNames -->
<!--   geneNames[nchar(geneNames)>0] -->
<!-- }) -->
<!-- names(list_vec_modGenes_moylan2013) = vec_mod_moylan2013 -->
<!-- ``` -->

Compute module-module gene intersect matrices

```{r}
fun = function(vec_genes) {
  sapply(list_vec_modGenes_perslab, function(vec_modGenes_perslab) { # column
    base::intersect(x=vec_genes, y=vec_modGenes_perslab) %>% length %>% '/'(length(vec_genes)) # row
  }, simplify=T)
}
```


```{r}
mat_moduleGeneIntersect_gerhard2018 <- sapply(FUN=fun,"X"=list_vec_modGenes_gerhard2018, simplify = T)
# set diagonal to zero
mat_moduleGeneIntersect_gerhard2018[col(mat_moduleGeneIntersect_gerhard2018)==row(mat_moduleGeneIntersect_gerhard2018)] <- 0
```

<!-- ```{r} -->
<!-- mat_moduleGeneIntersect_moylan2013 <- sapply(FUN=fun,"X"=list_vec_modGenes_moylan2013, simplify = T) -->
<!-- # set diagonal to zero -->
<!-- mat_moduleGeneIntersect_moylan2013[col(mat_moduleGeneIntersect_moylan2013)==row(mat_moduleGeneIntersect_moylan2013)] <- 0 -->
<!-- ``` -->

<!-- ```{r} -->
<!-- list_mat = list("gerhard2018"=mat_moduleGeneIntersect_gerhard2018,"moylan2013"=mat_moduleGeneIntersect_moylan2013) -->
<!-- ``` -->

plot these matrices

```{r}

# for (dataset in names(list_mat)) {
#   
#   mat_moduleGeneIntersect = list_mat[[dataset]]
#   
pdf(paste0(dirWGCNA_plots, prefixData, "_", prefixRun, "_", prefixRun_WGCNA, "_gerhard2018_mod_gene_overlap_with_perslab_", flagDate, ".pdf"),
    width=max(20,ncol(mat_moduleGeneIntersect_gerhard2018) %/% 3),
    height=max(20,ncol(mat_moduleGeneIntersect_gerhard2018) %/% 3))

corrplot(corr = mat_moduleGeneIntersect_gerhard2018, 
         method = "color",
         col = colorRampPalette(rev(brewer.pal(n = 11, name = "RdYlBu")), bias = 1)(200),
         diag = F,
         is.corr=F,
         title=paste0("prop. of Gerhard 2018 module (column) genes in perslab module (row)"),
         order = "original",#hclust",
         hclust.method = "average",
         addCoef.col = "black",
         tl.srt = 45,
         mar=c(3,3,3,3),
         number.digits = 2L,
         number.cex = 0.5)

invisible(dev.off())

```

wrap up

(nothing to do)

next:
liver_module_embed_in_moylan2013.Rmd 
liver_module_embed_in_gerhard2018.Rmd 
